In [1]:
import numpy as np
import math
import time

# Basic Sigmoid Function
def basic_sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

# Math Sigmoid Function
def math_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

# Vector Addition Example
x = np.array([1, 2, 3])
x = x + 3

# Sigmoid Derivative Function
def sigmoid_derivative(x):
    s = basic_sigmoid(x)  # Use vectorized sigmoid function for arrays
    ds = s * (1 - s)
    return ds

# Image to Vector Conversion
def imagetovector(image):
    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    return v

image = np.array([[[0.6765, 0.2765], [0.4765, 5.2765], [0.9765, 0.5765]],
                  [[0.6765, 0.2765], [0.4765, 5.2765], [0.9765, 0.5765]],
                  [[0.6765, 0.2765], [0.4765, 5.2765], [0.9765, 0.5765]]])

# Normalizing Data
def normalize(x):
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    x = x / x_norm
    return x

x1 = np.array([[0, 1000, 4], [2, 6, 4]])

# Softmax Function
def softmax(x):
    x_exp = np.exp(x - np.max(x, axis=1, keepdims=True))  # Improve stability
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = x_exp / x_sum
    return s

# Vectorization Examples
x1_vec = np.array([9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 0, 9, 2, 5, 0, 0])
x2_vec = np.array([9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 9])

# Dot Product
tic = time.process_time()
dot = np.dot(x1_vec, x2_vec)
toc = time.process_time()
dot_product_time = 1000 * (toc - tic)

# Outer Product
ticc = time.process_time()
outer = np.outer(x1_vec, x2_vec)
tocc = time.process_time()
outer_product_time = 1000 * (tocc - ticc)

# Outputs
print("basic_sigmoid(1):", basic_sigmoid(1))
print("math_sigmoid(1):", math_sigmoid(1))
print("x (after addition):", x)
print("sigmoid_derivative(1):", sigmoid_derivative(1))
print("sigmoid_derivative(2):", sigmoid_derivative(2))
print("Image to vector:", imagetovector(image))
print("normalize(x1):", normalize(x1))
print("softmax(x1):", softmax(x1))
print("Dot product =", dot, "\nComputation time =", dot_product_time, "ms")
print("Outer product =", outer, "\nComputation time =", outer_product_time, "ms")


basic_sigmoid(1): 0.7310585786300049
math_sigmoid(1): 0.7310585786300049
x (after addition): [4 5 6]
sigmoid_derivative(1): 0.19661193324148185
sigmoid_derivative(2): 0.10499358540350662
Image to vector: [[0.6765]
 [0.2765]
 [0.4765]
 [5.2765]
 [0.9765]
 [0.5765]
 [0.6765]
 [0.2765]
 [0.4765]
 [5.2765]
 [0.9765]
 [0.5765]
 [0.6765]
 [0.2765]
 [0.4765]
 [5.2765]
 [0.9765]
 [0.5765]]
normalize(x1): [[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]
softmax(x1): [[0.         1.         0.        ]
 [0.01587624 0.86681333 0.11731043]]
Dot product = 196 
Computation time = 0.0 ms
Outer product = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0 81]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0 18]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0 45]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0 63]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0 45]
 [ 0  0  0  0  0  0  0 